name: VisualTest(pull close)
on:
  pull_request:
    types: [closed]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Delete reg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        run: |
          num=`echo $GITHUB_REF | sed -r 's/^refs\/pull\/(.?)\/merge/\1/'`
          git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY} -b gh-pages .
          rm -rf $num
      - name: Save reg
        run: |
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email ${GITHUB_ACTOR}@git
          git add .
          git commit -m close
          git push origin gh-pages
